names = ['liubei', 'guanyu', 'zhangfei']
print("I want invide " + names[0] + names[1] + names[2] + " to my dinner")
print("But zhangfei cant come")
names.pop()
names.append('zhaoyun')
print(names)
print("I just find a bigger desk")
names.insert(0, 'huangzhong')
print(names)
names.insert(2, 'machao')
names.append('caocao')
print(names)
print("I can just invited two people to my dinner")
names.pop()
print("sorry caocao")
names.pop()
print("sorry zhaoyun")
names.pop()
print("sorry guanyu")
names.pop()
print("sorry macaho")
print(names[0] + " " + names[1])
print(names)
del names[0]
del names[0]
print(names)
